global_costmap:
  global_frame: map
  static_map: true

  # robot_base_frame: base_link
  # update_frequency: 5.0
  # width: 50
  # height: 50
  # rolling_window: true
  # plugins:
  #    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
  #    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}